### ISSUE TITLE
Detect MSI getting stuck on the missing package dialog during quiet uninstall

### ISSUE THREAD

**Issue by drdbkarron** [Klocman/Bulk-Crap-Uninstaller#10]
Visual studio installs hundreds of sub packages. I have dozens of versions of visual studio. The packages are saved in Program Data/Package Source.  I wrecked the PackageSource on my machine. I need to uninstall everything that says "Visual Studio" and reinstall Visual Studio all versions, flavours and kinds.

Revo Installer works but requires too much clicking. I would like to have this work and work quietly.

When MsiExec can't find the package source it starts a endless loop dialog for the user to enter the path to the package. This breaks your automation. It should be killed. This returns a failure code and does not do any cleanup.

I would like to look at the source code with you and see how you launch the subprocesses and if you can kill interactive processes hanging waiting on  user input without failing out.

**Comment by Klocman** [comment]
[This is where the check for orphaned MsiExec uninstallers happens.](https://github.com/Klocman/Bulk-Crap-Uninstaller/blob/master/UninstallTools/Uninstaller/BulkUninstallEntry.cs#L80) ([Link to documentation](https://msdn.microsoft.com/en-us/library/windows/desktop/aa370101(v=vs.85).aspx)) Even though more files are required, these uninstallers are technically still valid.

At the moment if an uninstaller fails, it is excluded from searching for leftovers for safety. Even if it was scanned for leftovers, the Msi uninstaller wouldn't be cleaned up properly because BCU doesn't know where to look.

One "fix" would be to add detection of Msi leftovers, detect that the Msi hung, and show the junk remove anyways.
