### ISSUE TITLE
Can't update from within BCUninstaller version 4.4 to 4.5 (win7 x64)

### ISSUE THREAD

**Issue by Jimbazuka** [Klocman/Bulk-Crap-Uninstaller#204]
Can't update from within bulk crap uninstaller version 4.4 to 4.5 (win7 x64) update failed
![2018-07-16 01_52_12-update failed](https://user-images.githubusercontent.com/7934633/42750159-0fd28b5c-889b-11e8-87ca-b2dfc6ded006.png)

**Comment by DmitriyYukhanov** [comment]
I confirm having this on my machine too.
Did a manual update to workaround.

**Comment by RCMoonpie** [comment]
I received the same error attempting to upgrade from version 4.3.4.38700 to 4.6.
It seems that there is no _Update.zip_ file in the folder.

Windows 10 Pro x64.

**Comment by Klocman** [comment]
The issue is that I don't have a good, working download location for the update files.

Starting now BCU will open the download page instead of trying to download an update that doesn't exist. Commit: 6e1661dd1275aed28ffb14b80cce32fc7c2974bc 

This will "fix" this error, but automatic update still won't work. Older BCU versions than around 4.4 now won't show that there's an update at all, until there's a valid download URL added.
