### ISSUE TITLE
FR: Support portable apps suites

### ISSUE THREAD

**Issue by myfairsyer** [Klocman/Bulk-Crap-Uninstaller#214]
Allthough portable app suites are (were?) probably mostly used on thumbdrives, I use them to make rarely-used and hardly-OS-integrated tools not mess with my OS.
For easy updating I usually keep them in a portable app suite/launcher like portableapps.com or liberkey (which on many computers resides in a cloud synced directory).

I have no idea how niche this use case is.

One problem is that you don't know where these suites reside

**Comment by myfairsyer** [comment]
If (!) BCU was to scan the MFT like I threw out in #215, it might be fast and easy to find those suites.
AFAIK PortableApps.com and Liberkey don't expect you to "properly uninstall" the apps, but you can just remove the folder, which the launchers recognize. I'm not 100% sure though.

As the portable apps of those suites (at least PortableApps.com's) are always organized in a certain structure , scanning the `MFT` might even enable us to easily detect portable installations that are independent of the suites/launchers.

**Comment by Klocman** [comment]
Since these launchers are almost always in the root directory of a drive and need to have a specific folder name it's very fast to check them even without scanning MFT.

BCU will now check for any common portable application directories on all fixed drives (enabled by default), and on removable drives (disabled by default).
