### ISSUE TITLE
Startup takes long time even with SSD

### ISSUE THREAD

**Issue by Jimbazuka** [Klocman/Bulk-Crap-Uninstaller#217]
BCU takes long time to "ingest" all programs compared to say Revo Uninstaller. Otherwise it rocks.

**Comment by Jimbazuka** [comment]
Windows 10 x64 SanDisk SSD i7-3720QM CPU

**Comment by Klocman** [comment]
Related to #168 #215 
How long does the scan take, and what parts of it take the longest?

**Comment by Jimbazuka** [comment]
how long it takes varies by  how many programs you have installed and the speed of your SSD. My SSD reaches 550 Mb/s and it takes about 18 seconds from launch to ready to uninstall. I estimate I have about 250 programs & apps installed on above SSD.

**Comment by Klocman** [comment]
I added some multithreading to application search, it should be faster on systems with SSDs or to a lesser extent multiple drives with applications. Depending on your settings, it should knock off a few seconds of your load time.

Unfortunately (?) BCU has a lot more data to go through than Revo in order to have the more thorough detection rate. Because of this it will always be slower by some amount. If I end up implementing basic/easy mode that should make BCU as fast as Revo, at the cost of some features.

I'm closing this for now, #168, #183 and #215 are what is needed to further improve startup time.

**Comment by Klocman** [comment]
@Jimbazuka Can you check if this build runs faster for you? 
[Debug.zip](https://github.com/Klocman/Bulk-Crap-Uninstaller/files/2431862/Debug.zip)

**Comment by Jimbazuka** [comment]
No its not faster but the latest v4.11 x64 is faster than before

**Comment by Klocman** [comment]
I added even more multithreading to 4.11, so that's probably why. Glad to hear it's getting better!
