### ISSUE TITLE
Same BCU version on 2 machines Win 10 x64 shows 2 different versions to same binary

### ISSUE THREAD

**Issue by Jimbazuka** [Klocman/Bulk-Crap-Uninstaller#225]
Same BCU version on 2 PCs running Win 10 x64 shows 2 different versions to same installed binary

BCU ver. 4.12.1.25773 (on both PCs) installed on two PCs running windows 10 x64 - in both machine the same binary (https://github.com/clsid2/mpc-hc/releases/download/1.8.4/MPC-HC.1.8.4.x64.exe) is installed.

In 1 machine this binary shows as correctly as version 1.8.4 
but on another machine it shows up as version 1.7.13 !!!!!!!!!!!

Same binary on Both PCs was a clean install (any previous version uninstalled by BCU complete with all registry keys deletion etc.)

Both binaries were MD5 compared (using CyoHash) and are identical (see attached)

![cyohash_md5_of_both](https://user-images.githubusercontent.com/7934633/50543111-8dfad680-0bc5-11e9-8163-0089c4bfb684.jpg)
![local-e-shows_up_correctly_1 8 4](https://user-images.githubusercontent.com/7934633/50543112-8dfad680-0bc5-11e9-88fd-5f0df0334e65.jpg)
![remote-x-mpc-hc_1 8 4-shows_up_as_1 17 3](https://user-images.githubusercontent.com/7934633/50543113-8dfad680-0bc5-11e9-8f86-2988bcde0c26.jpg)

**Comment by Klocman** [comment]
Make sure that MPC didn't automatically update itself, or the installer doesn't automatically download the newest version.

If it's the exact same files installed, please select the entry in BCU and click File > export on both systems and send the files.

**Comment by Jimbazuka** [comment]
I attach the "about" output from both MPC in both PCs (1 PC isd name E6530 the other is XPS) side-by-side so you can see they are the same version and did not auto-update. The Exported XML between the 2 shows the difference in version (also attached) - all 3 files are in the attached zip
[BCU-MPC.zip](https://github.com/Klocman/Bulk-Crap-Uninstaller/files/2730086/BCU-MPC.zip)

**Comment by Klocman** [comment]
I'm guessing that the 1.7 version was installed before, and then upgraded to 1.8. In these cases some installers don't update the version numbers.

You can check if this is the case by opening Windows Programs and Features, and checking the MPC version there. If it is the same as the one shown in BCU, this is the application's installer's issue, not BCU's (BCU correctly reports what the application is telling it).

**Comment by Jimbazuka** [comment]
Unfortunately, what you wrote above is not the case. Windows shows (correctly) version 1.8.4 while BCU still incorrectly shows  version 1.7.3 - see attached
![bcu_versions_mismatch](https://user-images.githubusercontent.com/7934633/51300525-24cbed80-1a24-11e9-8f60-3321b88941c2.jpg)

**Comment by Klocman** [comment]
It's very difficult to say what could be causing this because of how complex the information gathering process is.

My guess is that BCU scans the MPC install directory and pulls information about product name (`MPC-HC 1.7.13 (64bit)`) from one of the exe files that still has the old version info, and later on when merging this with the data from registry (that built-in Windows uninstaller uses), BCU decides that the 1.7.13 version is better and uses it instead of 1.8.4. Why this only happens on one PC, I'm not sure, most likely there's some difference in how or where MPC-HC was installed.

Since this is a rather benign issue (in a way BCU is right, some files do have a different version number), and how difficult it would be to "fix" this without causing a lot of other issues, I'll close this issue without a fix. It might get fixed in the future if I tweak the data collection code, but I can't promise it.

Thank you for the thorough bug report, and sorry I couldn't get it fixed!
