### ISSUE TITLE
Update UI for HiDPI monitors

### ISSUE THREAD

**Issue by anonymous-user** [Klocman/Bulk-Crap-Uninstaller#226]
I have a 1440p monitor and Windows 10 defaults to 125% scaling. Most applications are fine with this however I noticed that text in the Bulk-Crap-Uninstaller UI is very blurry.

Just in case my copy of BCUninstaller was outdated, I made sure to grab a copy of the latest 4.12.1 though it didn't change anything. It would be great if this could be addressed.

**Comment by Klocman** [comment]
Sadly this is a problem caused by .Net Framework version that BCU uses not having proper support for DPI scaling. To provide the best compatibility it uses .Net 3.5, while the required version for proper DPI handling is 4.7 included in Windows 10 Creator's update.

This is a planned upgrade and will happen when 4.7 runtime is more common.

**Comment by hugu48319** [comment]
I too would like to see HiDPI support.
How about updating the?

**Comment by Klocman** [comment]
Planned for next release.
