### ISSUE TITLE
Duplicates in leftovers

### ISSUE THREAD

**Issue by DmitriyYukhanov** [Klocman/Bulk-Crap-Uninstaller#231]
Hey, today I removed MS Office 2016 with all updates and it was kind of pain to inspect found leftovers since there were so much duplicates:

![image](https://user-images.githubusercontent.com/883587/52703185-cfd1b780-2f8e-11e9-82ea-8f4d54294887.png)

**Comment by Klocman** [comment]
I believe I fixed the duplicate entry issue within a single application.

Different updates having the same entries is by design however and will stay this way at least for now. To avoid this it would be necessary to combine applications, which would not always be what you want and could combine things by mistake.
