### ISSUE TITLE
Define Uninstaller Kind of scoop as "Scoop"

### ISSUE THREAD

**Issue by andrizmitnick** [Klocman/Bulk-Crap-Uninstaller#244]
it look's like any of scoop package are defined as "Powershell Script" in the Uninstaller Kind column. is it possible to change it to just "Scoop"?
thanks a lot before

**Comment by Klocman** [comment]
It is technically correct since PowerShell is used to uninstall these packages https://github.com/Klocman/Bulk-Crap-Uninstaller/blob/master/source/UninstallTools/Factory/ScoopFactory.cs#L141

Is there merit to adding Scoop as a separate type? You can still search for "scoop" to list its packages. Adding it would probably require some changes to make it behave like the current PowerShell type.

**Comment by andrizmitnick** [comment]
maybe is there a better way to search scoop installation?
i usually use filter "scoop" with Installation Location as Target Property.

**Comment by Klocman** [comment]
You can search for `scoop.ps1` with no additional filtering.

**Comment by andrizmitnick** [comment]
ah i got it, as simple as that. sorry for even creating such issue. thanks a lot!!
