### ISSUE TITLE
Context Menu Uninstall

### ISSUE THREAD

**Issue by robertheadley** [Klocman/Bulk-Crap-Uninstaller#247]
Since it is possible already to uninstall a program by locating the icon/shortcut anyway, is it possible to get a context menu option to uninstall. Similar to Windows, however Windows only opens the control panel.

**Comment by Klocman** [comment]
Do you mean add BCU to a shortcut context menu in windows explorer? It's an interesting suggestion, but I'm not sure how useful it would be, considering it wouldn't always work and you would still have to wait for BCU to load fully.

**Comment by Klocman** [comment]
Adding the context menu would have to be done by the BCU installer to avoid users moving BCU and breaking the context menus. The context menus would have to be on every single .exe so they would clutter the list, and BCU would have to start fully to uninstall the application and there's a chance that it would not be able to do so. Because of this I'm placing this suggestion in low priority until something major changes to make this more practical to implement.
