### ISSUE TITLE
New feature: Installation monitoring

### ISSUE THREAD

**Issue by Kratos-Mundus** [Klocman/Bulk-Crap-Uninstaller#258]
Hi can you add a feature for Monitoring new Installations?

**Comment by Klocman** [comment]
For now I don't plan on adding this feature. BCU is usually used some time after an application was installed, or as a portable app. It's also a bit heavy to have it constantly run in background, so a separate monitoring module would be needed.

Instead I prefer to improve "post-mortem" detection of junk because it will benefit the portable version as well as the installed version. Coding the monitor would require a fairly sizeable amount of time, so for now it's a low priority item. 

I'll close the issue for now, since no work will be done on this in the foreseeable future. If anyone wants to give implementing this a go then the issue can be reopened.

**Comment by garry-ut99** [comment]
> Klocman: It's also a bit heavy to have it constantly run in background, so a separate monitoring module would be needed.

Neither OP nor anybody said "constantly", it was about monitoring **installation**, means the monitoring is to be enabled only before & during installation of a new program + a first single run of the new program, then monitoring is saved and closed and will be reused during uninstallation in the future after orginal deinstallator finish and leave leftovers.

By the way I also replied to your previous comment in another duplicated thread: https://github.com/Klocman/Bulk-Crap-Uninstaller/issues/260 (related).

**Comment by Mannshoch** [comment]
As an Idea, [sandboxie](https://github.com/sandboxie-plus/Sandboxie) does something similar. 
And I know an [Window Backup application](https://www.heise.de/hintergrund/c-t-WIMage-3863074.html) that backup by using shadowcopy. In this case I assume you create a shadowcopy before installation and after installation and compare it.
