### ISSUE TITLE
crash at start

### ISSUE THREAD

**Issue by Vinayak-kadu** [Klocman/Bulk-Crap-Uninstaller#272]
i tried with latest 4.16 and with 4.15 version but even after successfull installation BCU wont start.. 
portatble version result the same..
i am on winows 8.1.

folllowing details i can get for crash

Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	BCUninstaller.exe
  Problem Signature 02:	4.16.0.38993
  Problem Signature 03:	5e2ca792
  Problem Signature 04:	System.Configuration
  Problem Signature 05:	4.8.3761.0
  Problem Signature 06:	5c9c7002
  Problem Signature 07:	28f
  Problem Signature 08:	28
  Problem Signature 09:	System.TypeInitialization
  OS Version:	6.3.9600.2.0.0.256.48
  Locale ID:	1033
  Additional Information 1:	6cd4
  Additional Information 2:	6cd458e8d3a8156eab014cd5e8b92198
  Additional Information 3:	0439
  Additional Information 4:	0439a291985b7c7aef45e679cccb41e0

**Comment by Klocman** [comment]
I'll need more details to fix this, at least a stack trace.

I'm currently porting BCU to .NET 5 and modernising parts of it, so your issue could be fixed by this in the next version. I'll close the issue for now, and if you still get the crash with the new version when it comes out, reopen this issue or start a new one.
