### ISSUE TITLE
does bcu have a list of bloatware it detects for uninstallation?

### ISSUE THREAD

**Issue by blesphy1** [Klocman/Bulk-Crap-Uninstaller#328]
sorry if the answer's obvious but is there a way for bcu to automatically check all the windows bloatware found on the system so they can be uninstalled? im not sure which features i should get rid of on my pc and how it might affect performance so i was wondering if there's a recommended list of things to get rid of. thanks

**Comment by Mullenders** [comment]
A priori, la colonne des "Notes des utilisateurs" devraient aider dans ce sens. Malheureusement, chez moi, seules mes propres notes d'utilisateur apparaissent sous forme d'étoiles noires. Pour les autres logiciels, aucune étoile dans cette colonne, seulement des termes comme "Inconnu" ou "Indisponible" ce qui, bien entendu, ne m'aide pas du tout. Quelqu'un peut-il me dire comment faire apparaître les notes des autres utilisateurs ?

**Comment by Klocman** [comment]
There is no pre-picked or autogenerated bloatware list.
BCU has a simple user ratings system where users can rate applications. You can use these ratings to get a rough idea of what's good or bad (take it with a grain of salt of course). The feature had issues for a while but will be fixed in the next release.
