### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by maris-mc** [Klocman/Bulk-Crap-Uninstaller#404]
Hello,
I'm a big Bulk Crap Uninstaller fan and used the program a lot. It's a super good and useful program, but I'm really missing a feature or I find a process relatively impractical. update that. Every time I want or want to update the program, I have to download the exe again. Isn't that easier? eg. Filezilla makes it much easier.
I hope that my criticism brings something.
Greetings Maris

**Comment by Klocman** [comment]
Automatic updates were a thing in the past but because of issues with finding a free host that allowed automated downloads I scrapped it (GitHub started blocking it because of large traffic). It also helps simplify the release process and keep current hosts happy, so it's unlikely to change for now.

**Comment by vedantmgoyal2009** [comment]
@Klocman After https://github.com/Klocman/Bulk-Crap-Uninstaller/issues/416 is merged, we can use `winget upgrade Klocman.BulkCrapUninstaller` to update BCUninstaller.

**Comment by NekoJonez** [comment]
Since #455 happened, shouldn't we close this one as fixed @Klocman ?

**Comment by Klocman** [comment]
Good call, thanks for the reminder!
