### ISSUE TITLE
Windows Defender triggered by "Virus:Win32/Neshta.A" upon setup of Bulk Crap?

### ISSUE THREAD

**Issue by Skyridr** [Klocman/Bulk-Crap-Uninstaller#424]
Once I installed this software, and it was doing its configuration, I got tons of microsoft defender warnings popping up on safe files:

![image](https://user-images.githubusercontent.com/6794064/201071827-d910b84c-8cef-4c63-834d-0b3e8de3f38b.png)

From that, to a lot of my gaming *.exe files. Any idea why this program is triggering Defender? Other files include eg, GTA 5 exe launcher.

**Comment by Klocman** [comment]
Don't want to bring bad news but looks like your PC is very infected, I suggest downloading and running MalwareBytes at the very least before using it for anything important. You might want to later change any passwords you entered while it was still infected too.

BCU looks at a lot of folders and files to build its application list. Windows Defender only scans files when they are accessed, so that's why it finds the viruses only after you run BCU. There's most likely even more of them that didn't get found yet.
