### ISSUE TITLE
"You require permission from SYSTEM"

### ISSUE THREAD

**Issue by ornithoptercat** [Klocman/Bulk-Crap-Uninstaller#441]
I'm finding that I can't fully delete some items - even if I enable "bad" confidence and check off stuff which is definitely related to them - because I get this error. 

I suspect this is closely related to the following apps simply failing to uninstall: 
[Microsoft] Call, Microsoft Content, Microsoft Edge, Microsoft Edge DevTools Client, Microsoft family features, Subscribed content (Auto-install suggested apps), Windows Hello Setup, Xbox Game UI

all of which are crap installed when I updated to Win10, of course. Anyone know how to fix this?

**Comment by Klocman** [comment]
Since some version of W10 Microsoft made it very difficult to remove their apps. They've been continually making it harder, closing down loopholes and automatically reinstalling them if you do manage to remove them, so I gave up on fighting it.

You may be able to find ways to remove these on the internet, but make sure they actually work on latest Windows version and are from a reputable source.

**Comment by MX-Mic** [comment]
While you're not going to run as SYSTEM you could probably get it working by running the program as TrustedInstaller. You can find the program to run as TrustedInstaller here: https://winaero.com/execti-run-programs-trustedinstaller/

**Comment by Klocman** [comment]
Moved to #447
