### ISSUE TITLE
[NEW] Tools > Clean up Registry

### ISSUE THREAD

**Issue by goyalyashpal** [Klocman/Bulk-Crap-Uninstaller#476]
The "Tools > **C**lean up "Program Files" folders..." help a lot. Can something similar be made for cleaning up registry?

I know that it coming up with such heuristic is quite hard, and providing such capability is super risky as well; will be sharing thoughts on these in comments below.

For a case study:
Before I found BCU, i was using RevoU. And it corrupted while uninstalling Python3.10
And it is a pain dealing with it now... I am manually `F3`-ing in `regedit` for python & deleting all enteries there... 
and there are lots of other such programs, which were uninstalled without any such leftover cleaners...

**Comment by goyalyashpal** [comment]
> CCLeaner

might be; as both RevoU & CC are from same co: Piriform

**Comment by Klocman** [comment]
Whitelists and blacklist are unworkable outside of universal tropes like "uninstall" or "update", because you'd have to have one for each of the supporting languages or users on on-English systems would be likely to not be protected by them and either have a non-usable feature or remove something important.

BCUninstaller is primarily for uninstalling applications, if you want to do a junk scan of files/registry then I recommend using BleachBit instead. You can integrate it with BCU if you need to, check settings > external tools.

**Comment by goyalyashpal** [comment]
> I recommend using BleachBit instead

following is from wikipedia, highlight mine. thanks for rec (:

> * BleachBit is a _free and open-source_ disk space cleaner, privacy manager, and computer system optimizer. The BleachBit source code is licensed under the _GNU General Public License_ version 3. 
> * History. BleachBit was first publicly released on 24 December 2008 for Linux systems. The 0.2.1 release created some controversy by suggesting Linux needed a registry cleaner.

**Comment by Klocman** [comment]
It sounds like you're happy with the solution so I'll close this issue.

> BTW,I think BCU can learn from Total Uninstall

Can you specify what exactly in a new issue?

**Comment by goyalyashpal** [comment]
> then I recommend using BleachBit instead

hi! do you have any FOSS recommendation for startup managers too?
