### ISSUE TITLE
Real portable version

### ISSUE THREAD

**Issue by CrypticCus** [Klocman/Bulk-Crap-Uninstaller#487]
I am requesting for a real portable version with option to chose save files to ini or registry. with only 1 executable file. Also please release versions without .net

I want 5-10 mb of the software not 130mb with requirements included.

**Comment by Klocman** [comment]
Settings are only saved inside the application directory. There is no registry option planned since BCU is foremost a portable tool.

A single executable is not possible, at least not without a major rewrite of the codebase. 

I share only standalone versions because of the amount of support requests about missing .Net frameworks. You can download the source and easily compile a non-standalone version for your own use.

**Comment by CrypticCus** [comment]
Yes i know that but, to compile a version without requirements i have to download 15+gb of visual studio with its depencisies. it is not practical for normal user. can u just share a version without it? like otp does with its releases?

**Comment by CrypticCus** [comment]
Also i tried to recompile it but couldn't even figure out how to remove depencies. I saw it in the list but there was no option to remove it. its hard you know for someone just to use your software.

**Comment by Klocman** [comment]
If you want to stray off the recommended path then of course it won't go as smoothly and require more tinkering. I'll consider adding a framework-dependant version but I can't promise anything.

**Comment by CrypticCus** [comment]
thank you very much framework dependant version would be great!

**Comment by CrypticCus** [comment]
thank you for the release
