### ISSUE TITLE
[EDITED: OPERATOR ISSUE] Detrimental/Dangrous: Uninstall wanted to "clean" whole directory (downloads), hit cancel... Completed erased anyway.

### ISSUE THREAD

**Issue by Derjyn** [Klocman/Bulk-Crap-Uninstaller#632]
As the title says. I was uninstalling a simple small app, BCU wanted to clean up "left over" files... NO NO NO. Hit cancel, a few seconds later, 300GB of files are completely gone.

There was no confirmation outside of the initial window that I hit cancel on. There were VERY important documents there. And NONE of those files were related to the installer (was a Windows utility, WinDbg).

I'm trying not to cry at the moment, and I can't even start to do an audit on what else was lost. Please be aware, anyone running this. It should be standard practice, but I've never had this issue with BCU and was fully expecting the "Cancel" button on the window that popped up to, you know, cancel the action of nuking the downloads directory. Generally that's what cancel or no means: don't do that action. Not "oh okay, go ahead and do it anyway and I won't double check to make sure you want to delete 300+ GB of files in a common Windows directory"

**Comment by stealthusk** [comment]
Ay man idk how tf that happened, but that sounds insane like holy shit. If you wanna talk about it, here's my Discord man: @cleanestturban

**Comment by Klocman** [comment]
Sorry, I have tested the junk removal window and could not get this to happen. If you could provide exact steps to reproduce this issue that would be helpful.

That being said, I find it hard to believe that it happened by pressing a "Cancel" button. I've double checked and the only way for BCU to remove any junk is to press "Delete selected" in the junk remove window, and then either Yes or No (not Cancel) in the dialog box asking to make a backup (unless backups were manually disabled beforehand, or no registry entries were checked since files are always moved to recycle bin even if backup is disabled). [Here's the code that runs the cleanup](https://github.com/Klocman/Bulk-Crap-Uninstaller/blob/14a2d0ec49f4eceacbaec0a99e6008e86693da0f/source/UninstallTools/Junk/Containers/FileSystemJunk.cs#L29-L36), the only reference to it is the accept button I've mentioned.

Even if it was removed through this window, it should have been placed into your recycle bin [by the code here](https://github.com/Klocman/Bulk-Crap-Uninstaller/blob/14a2d0ec49f4eceacbaec0a99e6008e86693da0f/source/UninstallTools/Junk/Containers/FileSystemJunk.cs#L29-L36).

**Comment by Derjyn** [comment]
It was driving me nuts up until a few days ago, to be honest I've gotten over it because there just isn't anything I can do. The code checks out, but... It happened. The 300 GB of files that got nuked were indeed too much for the recycle bin.

I can't remember the exact steps, it's been a bit. It was just a routine cleanup pass I was making, uninstalled a few things, etc. That download directory (central for my browsers, tools, anything that has downloads on a regular basis is configured to go here) was flagged for deletion.

I wasn't under the influence, I wasn't trigger happy... I have anxiety with confirmation dialogs and such, so I can say with absolute confidence having a dialogue asking about deletion of that folder would have had my utmost attention.

This is what I'm leaning on as a hail-Mary root cause theory: perhaps my system had a hitch, something I didn't catch between frames, and it caught a click on the confirm when to my eyes, it was on cancel. I've seen this sort of things on plenty of systems in my day, when drawing UI elements to the window and such have a hiccup and those various elements can catch user input in strange ways. That's the theory that lets me sleep at night.

**Comment by Klocman** [comment]
Looks like I pasted a wrong URL for the first link in my previous post, fixed that.

It does sound like a freak accident then, it's not really possible to know what exactly happened at this point. Did you check the recycle bin afterwards to see if there was anything in there?

**Comment by Derjyn** [comment]
Thanks for caring, and sorry if I drew any negative attention to the project. I've edited the title to be less jarring for potential viewers down the line.

Keep up the good work, and one final word of caution to others that stumble through here:

Make sure your system isn't experiencing any UI hiccups before hitting buttons. You may end up opening a black hole or creating a spacetime rift that will swallow petabytes!
