### ISSUE TITLE
change FW from 3.5 -> 4.x

### ISSUE THREAD

**Issue by KlausWilly** [Klocman/Bulk-Crap-Uninstaller#72]
Hi;
Thank's for the great tool.

Do you think you can change the neccesary Frameworkversion from 3.5 (not Default on Win10)
to Dotnet 4.0 (Win 10) ?

best wishes 
klaus

**Comment by Klocman** [comment]
Yes, it's definitely possible. In fact, all you have to do is change project settings to target 4.0. All code should work without changes.

The reason why BCU targets 3.5 is that Windows 7 comes with it pre-installed, and it's still the most common OS. Windows 10 will automatically offer to install 3.5 rather than throw up an error, so it's not as big of an issue.

That being said, Win 7 share is falling, so at some point I will retarget BCU to 4.0.
