### ISSUE TITLE
UI ENHANCEMENT REQUEST: Fluent Design

### ISSUE THREAD

**Issue by jebeld17** [Klocman/Bulk-Crap-Uninstaller#75]
BCU is definitely a powerhouse of an app we all know that, but the interface is not currently set to system scheme besides basic font and menu libraries, with the rest such as in-app text boxes (ie. the in-app message that appears during an unmatched search attempt in the search box) and buttons aren't tied to match anything of the system. 

_This UI fragmentation is enough already, in my humble opinion, to start development on a universal G/UI refresh._
**_With Microsoft finally revealing their plans for [Fluent Design](http://fluent.microsoft.com/), now is the perfect time to start planning a UI refresh that both is easier to use for the modern-day user and meets Microsoft's guidelines and specs._**

![screen_shot_2017_05_11_at_2 34 09_pm](https://cloud.githubusercontent.com/assets/9492083/26530264/b78a2fe0-439f-11e7-8881-6de870c2a8e9.png)
_(Above)_ File Manager prototype design using Microsoft's Fluent Design algorithms. More Fluent Design prototype apps are listed [**here in this news article by The Verge.**](https://www.theverge.com/2017/5/11/15625970/microsoft-fluent-design-desktop-email-app-ui)

##   

**Fluent Design Resources: 
_[Windows Dev Design Center](https://developer.microsoft.com/en-us/windows/apps/design)
[Windows Build2017 Press Kit](https://news.microsoft.com/build2017/)_**

**Comment by Klocman** [comment]
Hello!

I definitely agree that BCU's interface is dated, I don't think it's feasible to change it much. First of all, it would take A LOT of work. We are talking about a substantial rewrite for a non-commercial tool, which isn't used often. Still, I'm toying with the idea of making some minor changes.

Technical reasons moving to the new UI framework would be a pain:
- Everything around the application list would have to be re-done, because it all relies on ObjectListView, which is only available in WinForms.
- Microsoft wants people to use WinRT for the new UI, which means BCU wouldn't be able to access files and system functions as easily.
- I'm not sure how well the massive amount of information BCU is showing would translate into the new interface style. I'm guessing that it would look out of place anyways.

**Comment by jebeld17** [comment]
What about a new design that is made to appear like Fluent Design?

**Comment by Klocman** [comment]
Honestly, I'm not a fan of the new design. It focuses too much on hiding information and showing less content on the screen at the same time.
That being said, if someone else wanted to do update BCU's interface, I would support the effort.
