### ISSUE TITLE
For correction

### ISSUE THREAD

**Issue by Jhovany200** [Klocman/Bulk-Crap-Uninstaller#97]
In the part of the welcome to BCUninstaller in part 3/6 the texts in parts disappear the of descriptions

**Comment by Klocman** [comment]
It's because text next to the check boxes is too long to fill in a single line. It doesn't wrap around like normal labels. This is a problem with the Net Framework and can't be easily fixed.
![1](https://user-images.githubusercontent.com/14913904/29494031-7638e604-85a2-11e7-8eba-6fca22d49383.PNG)

You need to manually insert new lines in the translation of checkboxes to fix this. 
![2](https://user-images.githubusercontent.com/14913904/29494030-7633f9dc-85a2-11e7-873c-53d38a1ad654.PNG)

**Comment by Klocman** [comment]
Fixed it in ac2bbe6d7ea20d79c6683ff8ff8b70e88c4aa00d
